export const GET_SPOT_PRICE_REQUEST = "GET_SPOT_PRICE_REQUEST";
export const GET_SPOT_PRICE_SUCCESS = "GET_SPOT_PRICE_SUCCESS";
export const GET_SPOT_PRICE_FAILURE = "GET_SPOT_PRICE_FAILURE";

export default {
  GET_SPOT_PRICE_REQUEST,
  GET_SPOT_PRICE_SUCCESS,
  GET_SPOT_PRICE_FAILURE,
};
