export const GET_SPOT_PRICE_REQUEST = "GET_SPOT_PRICE_REQUEST";
export const GET_SPOT_PRICE_SUCCESS = "GET_SPOT_PRICE_SUCCESS";
export const GET_SPOT_PRICE_FAILURE = "GET_SPOT_PRICE_FAILURE";
export const GET_SPOT_PRICE_POLL_START = "GET_SPOT_PRICE_POLL_START";
export const GET_SPOT_PRICE_POLL_CANCEL = "GET_SPOT_PRICE_POLL_CANCEL";

export const GET_BUY_PRICE_REQUEST = "GET_BUY_PRICE_REQUEST";
export const GET_BUY_PRICE_SUCCESS = "GET_BUY_PRICE_SUCCESS";
export const GET_BUY_PRICE_FAILURE = "GET_BUY_PRICE_FAILURE";
export const GET_BUY_PRICE_POLL_START = "GET_BUY_PRICE_POLL_START";
export const GET_BUY_PRICE_POLL_CANCEL = "GET_BUY_PRICE_POLL_CANCEL";

export const GET_SELL_PRICE_REQUEST = "GET_SELL_PRICE_REQUEST";
export const GET_SELL_PRICE_SUCCESS = "GET_SELL_PRICE_SUCCESS";
export const GET_SELL_PRICE_FAILURE = "GET_SELL_PRICE_FAILURE";
export const GET_SELL_PRICE_POLL_START = "GET_SELL_PRICE_POLL_START";
export const GET_SELL_PRICE_POLL_CANCEL = "GET_SELL_PRICE_POLL_CANCEL";

export default {
  GET_SPOT_PRICE_REQUEST,
  GET_SPOT_PRICE_SUCCESS,
  GET_SPOT_PRICE_FAILURE,
  GET_SPOT_PRICE_POLL_START,
  GET_SPOT_PRICE_POLL_CANCEL,
  GET_BUY_PRICE_REQUEST,
  GET_BUY_PRICE_SUCCESS,
  GET_BUY_PRICE_FAILURE,
  GET_BUY_PRICE_POLL_START,
  GET_BUY_PRICE_POLL_CANCEL,
  GET_SELL_PRICE_REQUEST,
  GET_SELL_PRICE_SUCCESS,
  GET_SELL_PRICE_FAILURE,
  GET_SELL_PRICE_POLL_START,
  GET_SELL_PRICE_POLL_CANCEL,
};
