export const GET_SPOT_PRICE_REQUEST = "GET_SPOT_PRICE_REQUEST";
export const GET_SPOT_PRICE_SUCCESS = "GET_SPOT_PRICE_SUCCESS";
export const GET_SPOT_PRICE_FAILURE = "GET_SPOT_PRICE_FAILURE";
export const GET_SPOT_PRICE_POLL_START = "GET_SPOT_PRICE_POLL_START";
export const GET_SPOT_PRICE_POLL_CANCEL = "GET_SPOT_PRICE_POLL_CANCEL";

export default {
  GET_SPOT_PRICE_REQUEST,
  GET_SPOT_PRICE_SUCCESS,
  GET_SPOT_PRICE_FAILURE,
  GET_SPOT_PRICE_POLL_START,
  GET_SPOT_PRICE_POLL_CANCEL,
};
